plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}
version = "${mod_version}+mc${minecraft_version}"
group = maven_group
base { archivesName = 'kohs-hands-position' }
repositories {
    mavenCentral()
    maven { url = 'https://maven.terraformersmc.com/releases/' }
}
loom {
    splitEnvironmentSourceSets()
    mods {
        kohs_hands_position {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    compileOnly "com.terraformersmc:modmenu:${modmenu_version}"
    localRuntime "com.terraformersmc:modmenu:${modmenu_version}"
}
processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') { expand(version: project.version) }
}
tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = 'UTF-8'
}
java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}
